# Generated by Django 5.0.1 on 2025-05-10 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories', verbose_name='imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'atributo de producto',
                'verbose_name_plural': 'atributos de productos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='inventario')),
                ('available', models.BooleanField(default=True, verbose_name='disponible')),
                ('featured', models.BooleanField(default=False, verbose_name='destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products', verbose_name='imagen')),
                ('is_main', models.BooleanField(default=False, verbose_name='es principal')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='texto alternativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'imagen de producto',
                'verbose_name_plural': 'imágenes de productos',
                'ordering': ['-is_main', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='número de lote')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='fecha de producción')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='fecha de caducidad')),
                ('reorder_level', models.PositiveIntegerField(default=5, verbose_name='nivel de reorden')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_detail', to='products.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'inventario de producto',
                'verbose_name_plural': 'inventarios de productos',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='valor')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productattribute', verbose_name='atributo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'valor de atributo',
                'verbose_name_plural': 'valores de atributos',
                'unique_together': {('product', 'attribute')},
            },
        ),
    ]
