# Generated by Django 5.0.1 on 2025-05-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('phone', models.CharField(max_length=15, verbose_name='teléfono')),
                ('address', models.TextField(verbose_name='dirección')),
                ('city', models.CharField(max_length=100, verbose_name='ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='estado')),
                ('postal_code', models.CharField(max_length=10, verbose_name='código postal')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='estado')),
                ('payment_method', models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('deposito', 'Depósito Bancario'), ('efectivo', 'Pago en Efectivo')], default='transferencia', max_length=20, verbose_name='método de pago')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='subtotal')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='costo de envío')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='referencia de pago')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='cantidad')),
            ],
            options={
                'verbose_name': 'elemento de pedido',
                'verbose_name_plural': 'elementos de pedido',
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monto')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20, verbose_name='estado')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID de transacción')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de pago')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
            ],
            options={
                'verbose_name': 'información de pago',
                'verbose_name_plural': 'información de pagos',
            },
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='número de seguimiento')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='transportista')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('devuelto', 'Devuelto')], default='pendiente', max_length=20, verbose_name='estado')),
                ('shipped_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de envío')),
                ('delivered_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de entrega')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
            ],
            options={
                'verbose_name': 'información de envío',
                'verbose_name_plural': 'información de envíos',
            },
        ),
    ]
