# Generated by Django 5.0.1 on 2025-05-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='nombre del banco')),
                ('account_name', models.CharField(max_length=100, verbose_name='nombre del beneficiario')),
                ('account_number', models.CharField(max_length=20, verbose_name='número de cuenta')),
                ('clabe', models.CharField(max_length=20, verbose_name='CLABE')),
                ('payment_instructions', models.TextField(blank=True, verbose_name='instrucciones adicionales')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'configuración de pago',
                'verbose_name_plural': 'configuraciones de pago',
            },
        ),
    ]
